name: Backend CI/CD

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'backend-node/**'               # ðŸ‘‰ Only trigger when backend changes
      - '.github/workflows/backend.yml' # ðŸ‘‰ Also trigger when workflow itself changes

jobs:
  backend-deploy:
    runs-on: self-hosted

    steps:
      - name: ðŸ›Žï¸ Checkout repository
        uses: actions/checkout@v3

      - name: ðŸ”§ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ðŸ“¦ Install backend dependencies
        working-directory: ./backend-node
        run: npm install

      # ===========================================
      # DEV BACKEND DEPLOYMENT
      # ===========================================
      - name: ðŸš€ Restart Backend (DEV)
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "Restarting backend for DEV..."
          pkill node || true
          nohup node /home/ubuntu/Vite-app/backend-node/index.js > /home/ubuntu/backend-dev.log 2>&1 &
          echo "DEV backend restarted!"

      # ===========================================
      # PROD BACKEND DEPLOYMENT
      # ===========================================
      - name: ðŸš€ Restart Backend (PROD)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Restarting backend for PROD..."
          pkill node || true
          nohup node /home/ubuntu/Vite-app/backend-node/index.js > /home/ubuntu/backend-prod.log 2>&1 &
          echo "PROD backend restarted!"
